name: smhms_mobile
description: "Sistem Pemantauan Bahaya & Keselamatan (SMHMS) Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Pakej HTTP untuk panggil API Flask/Backend
  http: ^1.2.0

  # Pakej Getaran & Notifikasi
  vibration: ^2.0.1
  flutter_local_notifications: ^17.0.0

  # Visualisasi Data & Keselamatan (Tambahan Baharu)
  fl_chart: ^0.68.0
  local_auth: ^2.1.8
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true